import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const REGION_MAP: Record<string, string> = {
  "Seoul": "서울",
  "Busan": "부산",
  "Incheon": "인천",
  "Daegu": "대구",
  "Daejeon": "대전",
  "Gwangju": "광주",
  "Suwon": "수원",
  "Ulsan": "울산",
  "Changwon": "창원",
  "Goyang": "고양",
  "Yongin": "용인",
  "Seongnam": "성남",
  "Cheongju": "청주",
  "Jeonju": "전주",
  "Cheonan": "천안",
  "Ansan": "안산",
  "Namyangju": "남양주",
  "Anyang": "안양",
  "Gimhae": "김해",
  "Pyeongtaek": "평택",
  "Pohang": "포항",
  "Jeju": "제주",
  "Siheung": "시흥",
  "Paju": "파주",
  "Uijeongbu": "의정부",
  "Gimpo": "김포",
  "Gumi": "구미",
  "Gwangmyeong": "광명",
  "Wonju": "원주",
  "Jinju": "진주",
  "Asan": "아산",
  "Iksan": "익산",
  "Yangsan": "양산",
  "Chuncheon": "춘천",
  "Gyeongsan": "경산",
  "Gunpo": "군포",
  "Gunsan": "군산",
  "Yeosu": "여수",
  "Suncheon": "순천",
  "Gyeongju": "경주",
  "Geoje": "거제",
  "Mokpo": "목포",
  "Gangneung": "강릉",
  "Osan": "오산",
  "Chungju": "충주",
  "Icheon": "이천",
  "Yangju": "양주",
  "Sejong": "세종",
  "Hanam": "하남",
  "Guri": "구리",
  "Anseong": "안성",
  "Seosan": "서산",
  "Dangjin": "당진",
  "Andong": "안동",
  "Pocheon": "포천",
  "Uiwang": "의왕",
  "Gwangyang": "광양",
  "Gimcheon": "김천",
  "Jecheon": "제천",
  "Tongyeong": "통영",
  "Nonsan": "논산",
  "Sacheon": "사천",
  "Yeongju": "영주",
  "Miryang": "밀양",
  "Gongju": "공주",
  "Boryeong": "보령",
  "Sangju": "상주",
  "Yeongcheon": "영천",
  "Dongducheon": "동두천",
  "Taebaek": "태백",
  "Sokcho": "속초",
  "Mungyeong": "문경",
  "Samcheok": "삼척",
  "Gyeryong": "계룡",
  "Namwon": "남원",
  "Gimje": "김제",
  "Jeongeup": "정읍",
  "Naju": "나주"
}

export function translateRegion(region: string) {
  if (!region) return "-"
  return REGION_MAP[region] || region
}
